<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\MadWorldEU.Byakko.Core.Domain\Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Keycloak.AuthServices.Authentication" />
    <PackageReference Include="Keycloak.AuthServices.Sdk" />
  </ItemGroup>
</Project>
