{
 "title": "Byakko Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Uploads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(assets_uploads_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(assets_downloads_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted Asset meta datas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(assets_metadata_deletes_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted Asset contents",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(assets_content_deletes_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Correspondences Send",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(correspondences_feedback_sent_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}