apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: byakko-ingress-api
    namespace: {{ .Values.namespace }}
    annotations:
        kubernetes.io/ingress.class: "traefik"
        traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespace }}-security-headers@kubernetescrd
        traefik.ingress.kubernetes.io/service.serversTransport: {{ .Values.namespace }}-api-transport@kubernetescrd
        {{- if .Values.clusterIssuer.enabled }}
        cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer.name | quote }}
        {{- end }}
spec:
    ingressClassName: {{ .Values.ingress.className }}
    tls:
        - secretName: {{ .Values.ingress.tlsSecret }}-api
          hosts:
              - api.{{ .Values.ingress.domain }}
    rules:
        - host: api.{{ .Values.ingress.domain }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ .Values.api.name }}
                            port:
                                number: {{ .Values.api.servicePort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: byakko-ingress
    namespace: {{ .Values.namespace }}
    annotations:
        kubernetes.io/ingress.class: "traefik"
        traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespace }}-security-headers@kubernetescrd
        {{- if .Values.clusterIssuer.enabled }}
        cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer.name | quote }}
        {{- end }}
spec:
    ingressClassName: {{ .Values.ingress.className }}
    tls:
        - secretName: {{ .Values.ingress.tlsSecret }}
          hosts:
              - {{ .Values.ingress.domain }}
              - www.{{ .Values.ingress.domain }}
              - fileshare.{{ .Values.ingress.domain }}
              - admin.{{ .Values.ingress.domain }}
              - status.{{ .Values.ingress.domain }}
              - database.{{ .Values.ingress.domain }}
              {{- if .Values.observability.enabled }}
              - grafana.{{ .Values.ingress.domain }}
              {{- end }}
              {{- if .Values.headlamp.enabled }}
              - kubernetes.{{ .Values.ingress.domain }}
              {{- end }}
    rules:
        - host: admin.{{ .Values.ingress.domain }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ .Values.admin.name }}
                            port:
                                number: {{ .Values.admin.port }}
        - host: status.{{ .Values.ingress.domain }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ .Values.status.name }}
                            port:
                                number: {{ .Values.status.servicePort }}
        - host: database.{{ .Values.ingress.domain }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ .Values.pgadmin.name }}
                            port:
                                number: {{ .Values.pgadmin.servicePort }}
        - host: fileshare.{{ .Values.ingress.domain }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ .Values.portal.name }}
                            port:
                                number: {{ .Values.portal.port }}
        - host: www.{{ .Values.ingress.domain }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ .Values.portal.name }}
                            port:
                                number: {{ .Values.portal.port }}
        {{- if .Values.observability.enabled }}
        - host: grafana.{{ .Values.ingress.domain }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ .Values.observability.grafana.name }}
                            port:
                                number: {{ .Values.observability.grafana.servicePort }}
        {{- end }}
        {{- if .Values.headlamp.enabled }}
        - host: kubernetes.{{ .Values.ingress.domain }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ .Values.headlamp.name }}
                            port:
                                number: {{ .Values.headlamp.servicePort }}
        {{- end }}
        - host: {{ .Values.ingress.domain }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ .Values.portal.name }}
                            port:
                                number: {{ .Values.portal.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: byakko-ingress-auth
    namespace: {{ .Values.namespace }}
    annotations:
        kubernetes.io/ingress.class: "traefik"
        {{- if .Values.clusterIssuer.enabled }}
        cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer.name | quote }}
        {{- end }}
spec:
    ingressClassName: {{ .Values.ingress.className }}
    tls:
        - secretName: {{ .Values.ingress.tlsSecret }}-auth
          hosts:
              - authentication.{{ .Values.ingress.domain }}
    rules:
        - host: authentication.{{ .Values.ingress.domain }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ .Values.keycloak.name }}
                            port:
                                number: {{ .Values.keycloak.servicePort }}