apiVersion: v1
kind: ConfigMap
metadata:
    name: keycloak-theme-byakko
    namespace: {{ .Values.namespace }}
    labels:
        app: {{ .Values.keycloak.name }}
data:
    theme.properties: |
        parent=keycloak.v2
        internationalizationEnabled=true
        supportedLocales=en,nl,ja
        defaultLocale=en
    messages_en.properties: |
        termsText=<p>Please read our <a href="https://{{ .Values.ingress.domain }}/user-agreement" target="_blank" rel="noopener noreferrer">User Agreement</a> before continuing.</p>
    messages_nl.properties: |
        termsText=<p>Lees onze <a href="https://{{ .Values.ingress.domain }}/user-agreement" target="_blank" rel="noopener noreferrer">Gebruikersovereenkomst</a> voor je doorgaat.</p>
    messages_ja.properties: |
        termsText=<p>続行する前に<a href="https://{{ .Values.ingress.domain }}/user-agreement" target="_blank" rel="noopener noreferrer">利用規約</a>をお読みください。</p>
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.keycloak.name }}
    namespace: {{ .Values.namespace }}
    labels:
        app: {{ .Values.keycloak.name }}
type: Opaque
stringData:
    username: {{ .Values.keycloak.postgres.username | quote }}
    password: {{ .Values.keycloak.postgres.password | quote }}
---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.keycloak.name }}
    namespace: {{ .Values.namespace }}
    labels:
        app: {{ .Values.keycloak.name }}
spec:
    ports:
        - protocol: TCP
          port: {{ .Values.keycloak.servicePort }}
          targetPort: http
          name: http
    selector:
        app: {{ .Values.keycloak.name }}
    type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
    name: keycloak-discovery
    namespace: {{ .Values.namespace }}
    labels:
        app: {{ .Values.keycloak.name }}
spec:
    selector:
        app: {{ .Values.keycloak.name }}
    publishNotReadyAddresses: true
    clusterIP: None
    type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ .Values.keycloak.name }}
    namespace: {{ .Values.namespace }}
    labels:
        app: {{ .Values.keycloak.name }}
spec:
    serviceName: keycloak-discovery
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.keycloak.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.keycloak.name }}
        spec:
            automountServiceAccountToken: false
            containers:
                - name: {{ .Values.keycloak.name }}
                  image: "{{ .Values.keycloak.image }}:{{ .Values.keycloak.tag }}"
                  args: ["start"]
                  env:
                      - name: KC_BOOTSTRAP_ADMIN_USERNAME
                        value: {{ .Values.keycloak.adminUsername | quote }}
                      - name: KC_BOOTSTRAP_ADMIN_PASSWORD
                        value: {{ .Values.keycloak.adminPassword | quote }}
                      - name: KC_PROXY_HEADERS
                        value: "xforwarded"
                      - name: KC_HTTP_ENABLED
                        value: "true"
                      - name: KC_HOSTNAME_STRICT
                        value: "false"
                      - name: KC_HEALTH_ENABLED
                        value: "true"
                      - name: KC_CACHE
                        value: ispn
                      - name: KC_CACHE_STACK
                        value: kubernetes
                      - name: POD_IP
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: JAVA_OPTS_APPEND
                        value: '-Djgroups.dns.query="keycloak-discovery" -Djgroups.bind.address=$(POD_IP)'
                      - name: KC_DB
                        value: postgres
                      - name: KC_DB_URL_HOST
                        value: {{ .Values.keycloak.postgres.name }}
                      - name: KC_DB_URL_PORT
                        value: {{ .Values.keycloak.postgres.servicePort | quote }}
                      - name: KC_DB_URL_DATABASE
                        value: {{ .Values.keycloak.postgres.database }}
                      - name: KC_DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Values.keycloak.name }}
                                key: password
                      - name: KC_DB_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Values.keycloak.name }}
                                key: username
                  ports:
                      - name: http
                        containerPort: {{ .Values.keycloak.ports.http }}
                  startupProbe:
                      httpGet:
                          path: /health/started
                          port: {{ .Values.keycloak.ports.health }}
                      periodSeconds: 1
                      failureThreshold: 600
                  readinessProbe:
                      httpGet:
                          path: /health/ready
                          port: {{ .Values.keycloak.ports.health }}
                      periodSeconds: 10
                      failureThreshold: 3
                  livenessProbe:
                      httpGet:
                          path: /health/live
                          port: {{ .Values.keycloak.ports.health }}
                      periodSeconds: 10
                      failureThreshold: 3
                  volumeMounts:
                      - name: keycloak-theme-byakko
                        mountPath: /opt/keycloak/themes/byakko/login/theme.properties
                        subPath: theme.properties
                      - name: keycloak-theme-byakko
                        mountPath: /opt/keycloak/themes/byakko/login/messages/messages_en.properties
                        subPath: messages_en.properties
                      - name: keycloak-theme-byakko
                        mountPath: /opt/keycloak/themes/byakko/login/messages/messages_nl.properties
                        subPath: messages_nl.properties
                      - name: keycloak-theme-byakko
                        mountPath: /opt/keycloak/themes/byakko/login/messages/messages_ja.properties
                        subPath: messages_ja.properties
                  resources:
                      requests:
                          cpu: {{ .Values.keycloak.resources.requests.cpu }}
                          memory: {{ .Values.keycloak.resources.requests.memory }}
                          ephemeral-storage: {{ index .Values.keycloak.resources.requests "ephemeral-storage" }}
                      limits:
                          cpu: {{ .Values.keycloak.resources.limits.cpu }}
                          memory: {{ .Values.keycloak.resources.limits.memory }}
                          ephemeral-storage: {{ index .Values.keycloak.resources.limits "ephemeral-storage" }}
            volumes:
                - name: keycloak-theme-byakko
                  configMap:
                      name: keycloak-theme-byakko