namespace: "byakko-production"
imagePullPolicy: "IfNotPresent"
appVersion: "v0.8.1"
    
ingress:
    domain: "mad-world.eu"
    
clusterIssuer:
    enabled: true
    email: "changeme"
    
securityTxt:
    contact: "mailto:changeme"

headlamp:
    enabled: true

localstack:
    enabled: false

postgres:
    password: "changeme"

keycloak:
    adminPassword: "changeme"
    postgres:
        password: "changeme"

pgadmin:
    password: "changeme"

observability:
    enabled: true
    prometheus:
        storageSize: 50Gi
    tempo:
        storageSize: 20Gi
    loki:
        storageSize: 20Gi
    grafana:
        adminPassword: "changeme"
        keycloakClientSecret: "changeme"

api:
    encryption:
        key: "changeme"
        
storage:
    mode: "OvhCloud"
    ovhCloud:
        endpoint: "changeme"
        accessKey: "changeme"
        secretKey: "changeme"
        region: "changeme"